### ISSUE TITLE
0 folders found

### ISSUE THREAD

**Issue by delbs27** [segnolin/google-drive-folder-downloader#3]
Hey, 

If i run the command python download-2.py dir_name_local then drive.google.com url i get "0 folders found" with either the python 2 or 3 usage.

i have the credentials.json file downloaded successfully.  so it doesnt seem to be an auth problem.

**Comment by delbs27** [comment]
I can get it to find the folders now which is good. I cant get it to retrieve any of the files contained within though. does it have anything to do with the url defined within SCOPES variable?

**Comment by segnolin** [comment]
Thank you for using the script!

This script only finds the folder inside the “My Drive” and “Share” tabs in personal google drive, which means that unless you add the public share folder to your “Share” tab, it won’t find the folder. Also, the current script can only accept folder name, not url.

If there is only one folder that match the “folder_name” argument, it will directly download all the content inside the folder. If more than one match, it will let you choose which to download.

Regarding the SCOPES variable, I think drive.readonly is enough.
If the script still has the problem, please let me know, and if possible, please provide the step to reproduce, or some screenshots to let me investigate the issue. Thanks!

**Comment by rewiaca** [comment]
@segnolin thanks for explanation, that's not really handy to mark a bunch of publicly available google folders as a Shared to my account. Gonna look for another solution. Anyway, thanks for sharing.

**Comment by ahmettepe105** [comment]
ubuntu@ip:/var/www/html/aaa/gdriveup$ python download-2.py 111
1mcu1oWq86JOURlnpkJED5JYJkXM-o5Az 111
Traceback (most recent call last):
  File "download-2.py", line 131, in <module>
    main()
  File "download-2.py", line 61, in main
    download_folder(service, folder_id, location, unicode(folder_name, 'utf-8'))
TypeError: decoding Unicode is not supported
ubuntu@ip:/var/www/html/aaa/gdriveup$ 

sharefolder image : https://hizliresim.com/spE9Zy

Please help me.

**Comment by ahmettepe105** [comment]
0 folder found. 

error image and sharefolder : https://hizliresim.com/ZLZrhh

**Comment by segnolin** [comment]
You don't need to add `folder_name` to your command. You just need `python download-2.py test`

**Comment by segnolin** [comment]
Regarding to the unicode issue, I currently have no environment for python2 on ubuntu to test it out. I suggest using python3 because of its greater support for unicode. If you really need to use python2, I will investigate it more in depth.

**Comment by ahmettepe105** [comment]
python 3 error

ubuntu@ip/var/www/html/aaa/gdriveup$ python3 download.py depo
  File "download.py", line 37
    q=f"name contains '{sys.argv[1]}' and mimeType='application/vnd.google-apps.folder'",
                                                                                       ^
SyntaxError: invalid syntax
ubuntu@:/var/www/html/aaa/gdriveup$

**Comment by segnolin** [comment]
You need to use python3.6 at least to support f string.

**Comment by ahmettepe105** [comment]
ubuntu@ip/var/www/html/aaa/gdriveup$ python3.6 download.py depo
Traceback (most recent call last):
  File "download.py", line 3, in <module>
    from google_auth_oauthlib.flow import InstalledAppFlow
ModuleNotFoundError: No module named 'google_auth_oauthlib'
ubuntu@ip:/var/www/html/aaa/gdriveup$

**Comment by segnolin** [comment]
Please check out the latest commit and install the required dependencies (such as google_auth_oauthlib) and try if it works. Thanks!
